[project]
name = "hkust-hpc"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "sphinx>=8.2.3",
    "sphinx-copybutton>=0.5.2",
    "sphinx-rtd-theme>=3.0.2",
]
license = {text = "MIT"}
authors = [
    { name = "K. F. Tse", email = "kftse@ust.hk" },
    { name = "C. H. H. Tai", email = "chtaihei@ust.hk" },
]

[dependency-groups]
dev = [
    "black>=25.1.0",
    "doc8>=2.0.0",
    "docstrfmt>=1.11.1",
    "esbonio>=0.16.5",
    "flake8>=7.3.0",
    "isort>=6.0.1",
    "pre-commit>=4.3.0",
    "pylint>=3.3.8",
    "restructuredtext-lint>=1.4.0",
    "rstcheck>=6.2.5",
    "tox>=4.30.2",
    "typing-extensions>=4.15.0",
    "yamllint>=1.37.1",
    "yq>=3.4.3",
]

[tool.docstrfmt]
docstring-trailing-line = true
line-length = 120
