[project]
name = "hkust-hpc-doc"
authors = [
    {name = "kftse", email = "kftse@ust.hk"},
]
dynamic = ["version", "description"]
requires-python = ">=3.10"
dependencies = [
    "sphinx>=8.1.3",
    "sphinx-rtd-theme>=3.0.2",
]
version = "1.0.0"
description = "Documentation for HPC4"
readme = "README.md"
license = {text = "MIT"}

[tool.doc8]
ignore = ["D001"]

[tool.pdm]
distribution = false

[tool.pdm.dev-dependencies]
dev = [
    "doc8>=1.1.2",
    "esbonio>=0.16.5",
    "rstcheck>=6.2.4",
    "docutils>=0.21.2",
]
