[project]
name = "hkust-hpc"
license = {text = "MIT"}
organization = "The Hong Kong University of Science and Technology"
authors = [
    { name = "K. F. Tse", email = "kftse@ust.hk" },
    { name = "C. H. H. Tai", email = "chtaihei@ust.hk" },
]
description = "Default template for PDM package"
readme = "README.md"
dynamic = ["version"]

dependencies = [
    "sphinx-rtd-theme==3.0.2",
    "sphinx==8.1.3",
    "sphinx-copybutton==0.5.2",
]

requires-python = "==3.11.*"
# only supports linux cpython for contribution
platform = "manylinux_2_17_x86_64"
implementation = "cpython"
gil_disabled = true
version = "0.1.0"

[tool.setuptools_scm]
version_scheme = "guess-next-dev"
local_scheme = "node-and-hash"

[tool.pdm]
distribution = false

[tool.docstrfmt]
docstring-trailing-line = true
line-length = 88

[dependency-groups]
dev = [
    "doc8==1.1.2",
    "docstrfmt @ git+https://github.com/kftsehk/docstrfmt.git",
    "esbonio==0.16.5",
    "restructuredtext-lint==1.4.0",
    "rstcheck==6.2.4",
    "black==24.10.0",
    "flake8==7.1.1",
    "isort==5.13.2",
    "pdm==2.22.2",
    "pip==24.3.1",
    "pylint==3.3.3",
    "tox==4.23.2",
    "typing-extensions==4.12.2",
    "yamllint==1.35.1",
    "yq==3.4.3",
]
