[project]
authors = [{ name = "kftse", email = "kftse@ust.hk" }]
dependencies = ["sphinx-rtd-theme>=3.0.2", "sphinx>=8.1.3", "sphinx-copybutton>=0.5.2"]
description = "Documentation for HPC4"
dynamic = ["description", "version"]
license = { text = "MIT" }
name = "hkust-hpc-doc"
readme = "README.md"
requires-python = ">=3.10"
version = "1.0.0"

[tool.pdm]
distribution = false

[tool.doc8]
ignore = 'D001'
max-line-length = 10000

[tool.docstrfmt]
docstring-trailing-line = true
line-length = 10000

[dependency-groups]
dev = [
  "doc8>=1.1.2",
  "git+https://github.com/kftsehk/docstrfmt.git",
  "esbonio>=0.16.5",
  "restructuredtext-lint>=1.4.0",
  "rstcheck>=6.2.4",
  "black>=24.10.0",
  "flake8>=7.1.1",
  "isort>=5.13.2",
  "pdm>=2.22.0",
  "pip>=24.3.1",
  "pylint>=3.3.2",
  "tox>=4.23.2",
  "typing-extensions>=4.12.2",
  "yamllint>=1.35.1",
  "yq>=3.4.3",
]
